# Generated by Django 3.2.7 on 2021-09-08 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
    ]
