# Generated by Django 3.2.7 on 2021-09-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_product_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branches',
            new_name='catagory',
        ),
    ]
